@f_bdl_drop.sql
@f_bdl_drop_log.sql
@f_bdl_create_produit.sql
@f_bdl_create_produit_log.sql
@f_bdl_create_date.sql
@f_bdl_create_date_log.sql
@f_bdl_create_magasins.sql
@f_bdl_create_magasins_log.sql
@f_bdl_insert_dimensions.sql
@f_bdl_create_fact.sql
@f_bdl_create_fact_log.sql
@f_bdl_insert_fact.sql