@fobs_bdt_drop.sql
@fobs_bdt_drop_log.sql
@fobs_bdt_appelant.sql
@fobs_bdt_appelant_log.sql
@fobs_bdt_ville.sql
@fobs_bdt_ville_log.sql
@fobs_dbt_date.sql
@fobs_dbt_date_log.sql
@fobs_bdt_appels.sql
@fobs_bdt_appels_log.sql
@import_bde_bdt.sql